### ISSUE TITLE
How to distinguish eMMC or UFS?

### ISSUE THREAD

**Issue by adelinevanderpool17068** [maxim-saplin/CrossPlatformDiskTest#11]
![Screenshot_2020-06-05-12-37-12-595_com brave browser](https://user-images.githubusercontent.com/66236439/83838006-9b0ce500-a72a-11ea-9e5d-260d87f68f2a.jpg)

seems hard to do this.
Can you add some testing pattern like read/write ratio,50:50 25:75?

**Comment by maxim-saplin** [comment]
There's no explicit info about type of storage, the sole purpose of the chart is presenting the readings of CPDT for specific devices with basic specs (memory type is not generally available spec).

I believe you can do a research determining which devices have eMMC and which have certain version of UFS and device some rules (e.g. Seq. Read/Write thresholds) that will help judge by looking the the chart values.

Not sure I get what you suggested by some testing patterns... Specifically what's the goal. Also there's now 50/50 read write pattern: the first sequential test writes the whole file, the second test reads it completely.

**Comment by adelinevanderpool17068** [comment]
Dear Sir,
Thanks for your rapid reply!

I meant you can add a hybrid testing mode using multi-threads to read and write (sequencial and random)in the meantime.
To test the performance in full-duplex mode.
![UFS-1024x791](https://user-images.githubusercontent.com/66236439/83853861-7b84b500-a748-11ea-90d5-cdc3edb004af.jpg)
