### ISSUE TITLE
CPDT freeze if it can't delete written files

### ISSUE THREAD

**Issue by skytux** [maxim-saplin/CrossPlatformDiskTest#13]
It happens on Windows, when the created file by CPDT get locked by other program (nodepad++ here).

Nothing happens when clicking "Esc" link.

![image](https://user-images.githubusercontent.com/3109677/85400635-0511f080-b559-11ea-8999-954be0ce9ec6.png)

**Comment by skytux** [comment]
I can't even properly close it with the Quit link too : 

![image](https://user-images.githubusercontent.com/3109677/85401460-52db2880-b55a-11ea-9d64-de5fbc94a540.png)

Lets kill it trough taskmgr!

**Comment by maxim-saplin** [comment]
To be clear... You open the test file "E:\CPDT_TestFile.dat" while running the tests?

**Comment by skytux** [comment]
I was checking if it was only \0 or random data, it's sure to be not a
critical bug, there are more interesting tasks to do to be clear.

**Comment by maxim-saplin** [comment]
Not a use-case then, nothing to be done here...
