### ISSUE TITLE
System.UnauthorizedAccessException 

### ISSUE THREAD

**Issue by MadhavChoudhary** [maxim-saplin/CrossPlatformDiskTest#16]
How to run the benchmark on an external drive? It shows unauthorised access. I am using macOS Big Sur, but I am sure this is a general problem. Where do I give it permission/access? Any request doesn't show up in "Security & Privacy" Menu in System Preferences so that I can give it any access. I would expect it to request "Removable Volumes" in "File and Folders" part of "Privacy" Tab of "Security & Privacy" Menu of System Preferences.

**Comment by MadhavChoudhary** [comment]
Solved:

I had to manually give the app "Full Disk Access" in "Security & Privacy". It works after that. 
Would you make the change for it to request for specific permission? like other apps.

**Comment by maxim-saplin** [comment]
I'm on Big Sur now and CPDT seem to be working without any issues - tried it with USB flash, as well as with Windows shared folder over W-Fi.
Are you sure the reason is in the setting? Also, could you please share more details, what external drive you use.

**Comment by MadhavChoudhary** [comment]
I used a Seagate External HDD.

**Comment by MadhavChoudhary** [comment]
![Screenshot 2020-07-13 at 8 03 16 PM](https://user-images.githubusercontent.com/29799995/87316958-00cb6880-c544-11ea-9262-0203fa20de9d.png)
![Screenshot 2020-07-13 at 8 03 21 PM](https://user-images.githubusercontent.com/29799995/87316970-02952c00-c544-11ea-8e5a-01fa1a278300.png)

**Comment by maxim-saplin** [comment]
NTFS partition? Can you wirte files (e.g. copy paste in Finder) to the root directory? I believe you don't have Finder listed under "File and Folders"/"Privacy"

**Comment by MadhavChoudhary** [comment]
It is formatted as exFAT and I can write files to it. And no, I can't write files to my root directory from GUI. I can do that from terminal using "sudo". But wasn't this restriction the point of dividing into system and data volumes from Catalina?

**Comment by maxim-saplin** [comment]
To be clear
1. Finder can't copy/paste to the root folder of the external drive?
2. Manipulating files in the root folder is possible in Terminal with sudo?

**Comment by MadhavChoudhary** [comment]
1. Finder can copy/paste to the root folder of the external drive.
2. Manipulating files in the root folder of my computer's non volatile storage (128gb SSD) is possible in Terminal with sudo.

**Comment by maxim-saplin** [comment]
Will look into that when I have external HDD I can play with. Good to know there's no bug in the app though there might be some things to handle the situation in a more convenient way/ Thanks for letting me know
