### ISSUE TITLE
compilation error?

### ISSUE THREAD

**Issue by grbesd1** [maxim-saplin/CrossPlatformDiskTest#18]
Hi @maxim-saplin ,

I'm trying to compile source code in visual studio 19 community IDE with .netframework 4.8. I'm getting compilation errors.

I have downloaded android sdk-28, 29, 30.

>1>------ Build started: Project: Saplin.CPDT.UICore, Configuration: Debug Any CPU ------
>1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CPDT.Extra". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Saplin.StorageSpeedMeter". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\DriveTestViewModel.cs(3,14,3,31): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\TestResultsDetailed.cs(2,14,2,31): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\TestSession.cs(3,14,3,31): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\Views\Popups.xaml.cs(5,35,5,52): error CS0246: The type or namespace name 'BluredStackLayout' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\obj\Debug\netstandard2.0\Views\Popups.xaml.g.cs(17,71,17,88): error CS0234: The type or namespace name 'BluredStackLayout' does not exist in the namespace 'Saplin.CPDT.UICore.Controls' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\obj\Debug\netstandard2.0\Views\Options.xaml.g.cs(20,53,20,66): error CS0234: The type or namespace name 'ExtendedLabel' does not exist in the namespace 'Saplin.CPDT.UICore.Controls' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\Controls\RollingSelector.cs(14,36,14,49): error CS0246: The type or namespace name 'ExtendedLabel' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\DriveTestViewModel.cs(818,23,818,40): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\Views\Title.xaml.cs(45,16,45,29): error CS0246: The type or namespace name 'ExtendedLabel' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\DriveTestViewModel.cs(336,17,336,24): error CS0246: The type or namespace name 'BigTest' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\obj\Debug\netstandard2.0\Views\Title.xaml.g.cs(26,53,26,66): error CS0234: The type or namespace name 'ExtendedLabel' does not exist in the namespace 'Saplin.CPDT.UICore.Controls' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\DriveTestViewModel.cs(816,24,816,41): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\TestResultsDetailed.cs(9,23,9,40): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\ViewModels\TestResultsDetailed.cs(136,43,136,60): error CS0234: The type or namespace name 'StorageSpeedMeter' does not exist in the namespace 'Saplin' (are you missing an assembly reference?)
1>C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\Controls\KeyPress.cs(426,23,426,36): error CS0246: The type or namespace name 'ExtendedLabel' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "Saplin.CPDT.UICore.csproj" -- FAILED.
2>------ Build started: Project: Saplin.CPDT.Android, Configuration: Debug Any CPU ------
3>------ Build started: Project: Saplin.CPDT.Mac, Configuration: Debug Any CPU ------
4>------ Build started: Project: Saplin.CPDT.WPF, Configuration: Debug Any CPU ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CPDT.Extra". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
3>  Consider app.config remapping of assembly "netstandard, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" from Version "2.0.0.0" [] to Version "2.1.0.0" [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Facades\netstandard.dll] to solve conflict and get rid of warning.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
3>CSC : error CS0006: Metadata file 'C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\bin\Debug\netstandard2.0\Saplin.CPDT.UICore.dll' could not be found
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CPDT.Extra". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CPDT.Extra.Android". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CPDT.Extra". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Saplin.StorageSpeedMeter". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>CSC : error CS0006: Metadata file 'C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\bin\Debug\netstandard2.0\Saplin.CPDT.UICore.dll' could not be found
2>CSC : error CS0006: Metadata file 'C:\Users\ITC\Desktop\CrossPlatformDiskTest-master\CrossPlatformDiskTest-master\Saplin.CPDT.UICore\bin\Debug\netstandard2.0\Saplin.CPDT.UICore.dll' could not be found
`

**Comment by maxim-saplin** [comment]
The libs are here: https://github.com/maxim-saplin/CrossPlatformDiskTest/tree/master/References

I assume you try building the proect in DEBUG configuration. There're path overrides in .csproj files which point to paths that are specific to y env, you might need to change them to the above location. E.g. here're the overrides in Saplin.CPDT.UICore.csproj:

```
  <ItemGroup>
    <Reference Include="CPDT.Extra">
      <HintPath Condition="'$(Configuration)'=='Debug'">..\..\CPDT.Extra.git\CPDT.Extra\bin\Debug\netstandard2.0\CPDT.Extra.dll</HintPath>
      <HintPath Condition="'$(Configuration)'=='Release'">..\References\CPDT.Extra.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Posix.NETStandard">
      <HintPath>..\References\Mono.Posix.NETStandard.dll</HintPath>
    </Reference>
    <Reference Include="Saplin.StorageSpeedMeter">
      <HintPath Condition="'$(Configuration)'=='Debug'">..\..\NetCoreStorageSpeedTest.git\Saplin.StorageSpeedMeter\bin\Debug\netstandard2.0\Saplin.StorageSpeedMeter.dll</HintPath>
      <HintPath Condition="'$(Configuration)'=='Release'">..\References\Saplin.StorageSpeedMeter.dll</HintPath>
    </Reference>
  </ItemGroup>
```
