### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by jpzex** [maxim-saplin/CrossPlatformDiskTest#20]
At the [CPDT Website](https://maxim-saplin.github.io/cpdt_results/?about=) near the beginning, there is a mispelling at the phrase: "At least 3 test runs are done, for each of the 5 **perfromance** metrics the best one is selected." I'll revise all the text there and return feedback if is there any other mistake. Thanks for the great app!

**Comment by jpzex** [comment]
"Since lack of free disk space affects performance (very noticable on mobile devices) **testting** is conducted at at least 70% of available space on the drive."

Also about this part, does it mean at least 30% free? Because if so, the way it's written can be misleading (people can think 70% free is needed). A suggestion would be: "is conducted only if at least 30% of storage space is available."

**Comment by jpzex** [comment]
"In case OS receives subsequent file read/write requests through API it will simply copy the cached memory pages from previous file operations and not utilize the actual storage device. Turning this option on is **essential** a test of OS's file caching subsystem and RAM speed, rather than storage device test."

Might it be "essentially"? if not, the phrase should change to "Turning this option on is **essential to test the** OS's file caching subsystem and RAM speed, rather than storage device test."

I guess that's all. 👍

**Comment by maxim-saplin** [comment]
Thanks!
Fixed the mistakes.

-  "is conducted only if at least 70% of storage space is available." - it's 70% of free space

- "Turning this option on is essential a test of OS's file caching"  - essetinaly/effectively testing of OS's file caching

-
