### ISSUE TITLE
Add Results HP 15-db1070ur

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#21]
**Model:** HP 15-db1070ur
**Year:** 2019
**RAM:** 8Gb
**Storage:** SSD M.2, 256 Gb (_MTFDHBA256TCK-1AS1AABHA_)
**CPU:** AMD Ryzen 3 3200U

**System:** Windows 10 20H2 x64
**Program version:** CPDT 2.3.3

![Снимок экрана 2021-01-18 140339](https://user-images.githubusercontent.com/36500228/105534290-54421e80-5cfe-11eb-8bf0-eec81f1bd1c7.png)

**Comment by maxim-saplin** [comment]
Add to the DB. Thanks Artem!
