### ISSUE TITLE
Add Results POCO M3

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#23]
**Model:** M2010J19CG
**Year:** 2020
**RAM:** 4Gb LPDDR4X
**Storage:** 64Gb UFS (2.1?)
**CPU:** Snapdragon 662

**System:** Android 10, MIUI 12.0.4
**Program version:** CPDT 2.3.7

![Screenshot_2021-02-27-22-54-00-372_com Saplin CPDT](https://user-images.githubusercontent.com/36500228/109399176-46616800-7952-11eb-9dda-00ab176f5d79.jpg)

**Comment by maxim-saplin** [comment]
Done!
