### ISSUE TITLE
Write speed results off by an order of magnitude on Linux

### ISSUE THREAD

**Issue by mkraft** [maxim-saplin/CrossPlatformDiskTest#29]
Tested across several Linux machines and CPDT reports around 400MB/s consecutive write speeds whereas KDiskMark correctly reports around 10x that.

**Comment by maxim-saplin** [comment]
Could you please share more detail? What hardware/software configs did you use, what kind of figures you received in CPDT and KDiskMark?

I've just tried this app in Ubuntu, it gave insanely high numbers for Read speed (also the UI clips the results, had to hover to see the results) which raises concerns if the program can disable in-memory caches OR if there're other issues with the algo.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/7947027/116471996-fb929c80-a87d-11eb-94ce-ec5c0c1ec840.png">

**Comment by mkraft** [comment]
If you do something like this:

```bash
fallocate -l 5G foo
time cp foo /other/directory/
```

Does it take closer to 1 second or 16 seconds?
