### ISSUE TITLE
Close to desktop on Note 10+

### ISSUE THREAD

**Issue by ironjohn** [maxim-saplin/CrossPlatformDiskTest#3]
Thanks for the time you are putting into this project guys!

I needed to test some SD cards in my Note 10+ and went to Play Store looking for A1.  I was happy to see your project and tried it first, but CPDT crashed to desktop twice before it finished.  Once on internal storage and again on a 128gb Sandisk A2 U3 card.

Let me know what I can do to help.  I don't mind reinstalling and collecting log files or whatever.

-John

**Comment by maxim-saplin** [comment]
Thanks for submitting the issue. My suspect is the mechanism for fighting memory caching. Essentiality it purges whatever data is cached in memory by allocating as much free RAM as possible. In some cases this may lead to OS killing the app. Cu

I have to look into it and see how the app can allocate memory in a clever way and stop doing this as soon as Android is about to kill the app.
