### ISSUE TITLE
Add Results Lenovo A536

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#31]
**Model:** A536
**Year:** 2014
**RAM:** 1 Gb LPDDR2
**Storage:** 8 Gb MMC
**CPU:** MediaTek MT6582

**API:** 19
**System:** Android 4.4.2, A536_S186_150813_ROW
**Program version:** CPDT 2.3.8

![Screenshot_2021-05-10-14-16-07](https://user-images.githubusercontent.com/36500228/117883521-2afccc80-b2b4-11eb-8a5f-e15212c4eaee.png)

**Comment by maxim-saplin** [comment]
Большое спасибо! Добавил.
