### ISSUE TITLE
Running this as a console app

### ISSUE THREAD

**Issue by shivanshu3** [maxim-saplin/CrossPlatformDiskTest#33]
Hi, do you any plans of making this a console app? Running it on a headless server is not possible. Making it a curses based app would be very helpful.

**Comment by maxim-saplin** [comment]
Hi. Please check this out https://github.com/maxim-saplin/NetCoreStorageSpeedTest

**Comment by shivanshu3** [comment]
Thank you, that is perfect! Adding this link to the README file might help more people find it :)

**Comment by maxim-saplin** [comment]
There's a link) Though it says the console app is for Linux which van be confusing (since there're also Win and Mac versions)
