### ISSUE TITLE
Add Results LeEco Le 2

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#35]
**Model:** X527
**Year:** 2016
**RAM:** 3 Gb LPDDR3
**Storage:** 32 Gb MMC
**CPU:** Qualcomm Snapdragon 652 (MSM8976)

**API:** 23
**System:** Android 6.0.1, EUI 5.8.019S
**Program version:** CPDT 2.3.9

![Screenshot_20210617-040905](https://user-images.githubusercontent.com/36500228/122614352-2683ba80-d08f-11eb-9bcb-b277382cb09e.jpg)

**Comment by maxim-saplin** [comment]
Added
