### ISSUE TITLE
Add Results Sony Xperia XZ2

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#36]
**Model:** H8266
**Year:** 2018
**RAM:** 4 Gb LPDDR4X
**Storage:** 64 Gb UFS 2.0?
**CPU:** Qualcomm Snapdragon 845

**API:** 29
**System:** Android 10, 52.1.A.3.49
**Program version:** CPDT 2.3.9

![Screenshot_20210623-223653](https://user-images.githubusercontent.com/36500228/123521057-f9ea2700-d6bc-11eb-8574-1d7d59288579.png)

**Comment by maxim-saplin** [comment]
Added
