### ISSUE TITLE
Add results Asus N73SV

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#37]
**Model:** N73SV
**Year:** 2011?
**RAM:** 4 Gb DDR3-1333
**Storage:** SSD SATA 256 Gb _(WDC WDS120G2G0A-00JH30)_
**CPU:** Intel Core i3-2310M

**System:** Windows 10 Pro 20H2 x64
**Program version:** CPDT 2.3.3

![Снимок экрана 2021-05-10 173634](https://user-images.githubusercontent.com/36500228/123521900-32403400-d6c2-11eb-90fe-5326a775c889.png)

**Comment by maxim-saplin** [comment]
Done
