### ISSUE TITLE
Add Results ASUS VivoBook S14 

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#43]
**Model:** M433IA-EB885T
**Year:** 2021?
**RAM:** 8Gb
**Storage:** SSD M.2, 256 Gb (_HFM256GDJTNG-8310A_)
**CPU:** AMD Ryzen 5, 4500U

**System:** Windows 10 21H1 x64
**Program version:** CPDT 2.3.3

<img width="638" alt="Снимок экрана 2021-08-30 235343" src="https://user-images.githubusercontent.com/36500228/132329929-33f4b860-2e46-42d6-8738-82d5239c607b.png">

**Comment by maxim-saplin** [comment]
Done
