### ISSUE TITLE
Add Results Redmi 9T 4/64Gb

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#44]
**Model:** ?
**Year:** 2021
**RAM:** 4 Gb (LPDDR4X?)
**Storage:** 64 Gb (UFS 2.1?)
**CPU:** Qualcomm Snapdragon 662

**API:** ?
**System:** Android 10, MIUI 12.0.5.0
**Program version:** CPDT 2.3.9

![Screenshot_2021-09-24-20-51-10-786_com Saplin CPDT](https://user-images.githubusercontent.com/36500228/134785657-8c65ba9f-5385-4688-a9cd-0161566e1479.jpg)

**Comment by maxim-saplin** [comment]
Done
