### ISSUE TITLE
Add Huawei MediaPad T3 8.0

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#45]
**Model:** KOB-L09
**Year:** 2017?
**RAM:** 2 Gb
**Storage:** 16 Gb?
**CPU:** Qualcomm Snapdragon 662

**API:** ?
**System:** Android 7, EMUI 5.1.3 (KOB-L09C170B280)
**Program version:** CPDT 2.3.9

![Screenshot_20210924-203403](https://user-images.githubusercontent.com/36500228/134967590-edd58a73-295a-4629-951f-4672bec27ea1.png)

**Comment by maxim-saplin** [comment]
Done
