### ISSUE TITLE
Add Motorola DROID Turbo

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/CrossPlatformDiskTest#48]
**Model:** ?
**Year:** 2014
**RAM:** 3 Gb?
**Storage:** ?
**CPU:** Qualcomm Snapdragon 805  

**API:** ?
**System:** ?
**Program version:** ?

Скриншот из сообщения пользователя **StorMka**, с форума **4PDA**
![Screenshot_20211006-101828_Trebuchet](https://user-images.githubusercontent.com/36500228/136661445-a32162b6-6d07-4dd6-bdd7-db2ca19be82c.png)
https://4pda.to/forum/index.php?s=&showtopic=596451&view=findpost&p=109967902

Скриншот из сообщения пользователя **Xaiit**, с форума **4PDA**
![Screenshot_20211007-151950](https://user-images.githubusercontent.com/36500228/136661602-83c80e57-ba70-4b43-bc23-777193817495.png)
![Screenshot_20211007-152555](https://user-images.githubusercontent.com/36500228/136661605-a8ef02b5-e63c-4439-955e-009767b314cf.png)
https://4pda.to/forum/index.php?s=&showtopic=596451&view=findpost&p=109987237

**Comment by maxim-saplin** [comment]
Done
