### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by HaleTom** [maxim-saplin/CrossPlatformDiskTest#5]
This is an excellent tool to compare how OS and hardware affects SD speeds.

To be truly cross-platform, could Linux be supported?

(I'm suspect about the quality of my built-in sdcard reader in my Linux laptop)

**Comment by HaleTom** [comment]
I see at the top of [this page](https://maxim-saplin.github.io/cpdt_results/?about=) the Linux linked page talks about Linux support, but I can't see any Linux releases.

**Comment by maxim-saplin** [comment]
Hi, thanks for the interest in the app. The Linux version is a command line tool based on the same measuring lib and sits in a different repo: https://github.com/maxim-saplin/NetCoreStorageSpeedTest

Though currently there seem to be an issue on some Linux distribs with the tool filtering out some partitions (havent looked into the issue yet).

**Comment by HaleTom** [comment]
Sweet!  Could you perhaps mention the Linux version in the README of this project?

**Comment by maxim-saplin** [comment]
Indeed, no mention in this repo... Will add.
