### ISSUE TITLE
Test file not get deleted after test completion. 

### ISSUE THREAD

**Issue by Dark-Cod3r** [maxim-saplin/CrossPlatformDiskTest#6]
Hi. I am not sure if its expected behavior or not but everytime we run a test, at the end of the test it wont delete test file hence filling out space. Check the below screenshot, i ran test 4 times with 1 GB file size... Hope you will look into this issue. Thank You
![Screenshot_2020-02-05-12-19-11-505_com google android diskusage](https://user-images.githubusercontent.com/6500557/73819809-2f654a80-4812-11ea-8842-7e8deb611e46.jpg)

**Comment by maxim-saplin** [comment]
Could you please few details.
1. Androud version
2. App version
3. Installed from GPlay?
4. Phone model
5. Did the tests succeed? Didn't the app crashed? 

Test file can be left undeleted if the app crashes, thoug consequent test run will rewrite the test file and delete it. Also the file is also the same and it doesn't make sense that 4 test runs can produce 4 test files.

Could you please check App Info for CPDT and see what Storage shows?

![Screenshot_20200205-105636_Settings](https://user-images.githubusercontent.com/7947027/73822626-2fa81a80-47ff-11ea-8d78-42e4a2b06e92.jpg)
![Screenshot_20200205-105639_Settings](https://user-images.githubusercontent.com/7947027/73822641-3767bf00-47ff-11ea-9f58-7a16d86f72ac.jpg)

**Comment by Dark-Cod3r** [comment]
Hi. Kindly check these below screenshots for android version and app info. 
Yes, all 4 times test completed successfully..
![Screenshot_2020-02-05-13-08-32-753_com android settings](https://user-images.githubusercontent.com/6500557/73822883-f11f5980-4818-11ea-8530-6840b71c2430.jpg)
![Screenshot_2020-02-05-13-08-05-347_com miui securitycenter](https://user-images.githubusercontent.com/6500557/73822891-f381b380-4818-11ea-9b79-bbbad8cfb612.jpg)
![Screenshot_2020-02-05-13-08-01-948_com miui securitycenter](https://user-images.githubusercontent.com/6500557/73822893-f41a4a00-4818-11ea-9eff-e6da00095e00.jpg)

**Comment by Dark-Cod3r** [comment]
Here. Check this.. i ran a test again and it completed successfully , but again as it says file deleted but it didnt (size increase from 4 to 5GB).
![Screenshot_2020-02-05-13-13-59-006_com Saplin CPDT](https://user-images.githubusercontent.com/6500557/73823207-96d2c880-4819-11ea-89f0-ebbf7b956dc3.jpg)
![Screenshot_2020-02-05-13-14-13-811_com miui securitycenter](https://user-images.githubusercontent.com/6500557/73823214-99cdb900-4819-11ea-98a0-898b89c14e64.jpg)

**Comment by maxim-saplin** [comment]
Thanks!

I assumed you picked option [2]/ It'd be great if you checked apps folder via File Explorer (stock app should be fine) at "Internal Storage -> Android -> Data -> com.Saplin.CPDT" and see if there're any files.

Besides, any chance you have a custom ROM with no "Android System WebView" app installed?

Also, could you please remove the app and try the one from APK? https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.3.1/com.Saplin.CPDT.apk

**Comment by Dark-Cod3r** [comment]
Hi. That folder location is empty. Also one more thing i notice is even after uninstalling app, data is still present (cause free space is still same). Means it consuming storage space but not freeing it up even after uninstalling.
Yes, ROM has webview (using chrome for webview render).
I did try your given apk, same issue. 
![Screenshot_2020-02-05-13-31-07-186_com android settings](https://user-images.githubusercontent.com/6500557/73825293-8a506f00-481d-11ea-8bc2-fddf192e3192.jpg)
![Screenshot_2020-02-05-13-32-10-758_com mixplorer](https://user-images.githubusercontent.com/6500557/73825298-8cb2c900-481d-11ea-9f1a-236fc0042dbb.jpg)
![Screenshot_2020-02-05-13-43-21-951_com miui securitycenter](https://user-images.githubusercontent.com/6500557/73825302-8de3f600-481d-11ea-9869-09b7887d4b1d.jpg)

**Comment by Dark-Cod3r** [comment]
Here.. notice system data and apps data space changes. Data is still present somewhere in it but its not showing up (probably hidden or something)... 
![Screenshot_2020-02-05-13-49-13-209_com google android diskusage](https://user-images.githubusercontent.com/6500557/73825962-bfa98c80-481e-11ea-93fb-5e94021d0acf.jpg)
![Screenshot_2020-02-05-13-50-22-194_com google android diskusage](https://user-images.githubusercontent.com/6500557/73825981-c6380400-481e-11ea-9927-5c8c444b9eee.jpg)

 
![Screenshot_2020-02-05-13-47-04-581_com google android diskusage](https://user-images.githubusercontent.com/6500557/73825935-b5878e00-481e-11ea-9087-6f5ba1a9a1ca.jpg)
![Screenshot_2020-02-05-13-50-15-736_com google android diskusage](https://user-images.githubusercontent.com/6500557/73825948-bae4d880-481e-11ea-8694-1cd60ac152ff.jpg)

**Comment by maxim-saplin** [comment]
MIUI had a nice disk cleanup util in Settings or Security app. Under Deep Cleaning there was a section listing large files - can you check it?

**Comment by Dark-Cod3r** [comment]
yeah, i did tried that cleanup but it didnt detect that file. so i rebooted my phone and all storage space back to normal. (now 20+GB free space).. 
so then i tried another thing, i ran another test, after successful completion i checked and and its occupying 1GB(even though app says file deleted successfully) , so i rebooted and all storage space back to normal.  
So to completely remove all test data file of this app i need to reboot to fix that (this only specific to CPDT app). other apps (like A1 SD bench dont have this issue). So probably it has something to do with the way CPDT delete test file.. also i am on f2fs file system (not sure if this has something to do with it)...

**Comment by maxim-saplin** [comment]
From your description I can imply that file-system metadata somehow doesn't get updated, when the file is created the free space is decreased while when it is deleted the free space isn't clocked back, After the reboot free space gets re-conciliated. There might be some workaround that CPDT might apply to force metadata updates. Though given no actual space is lost and the file is deleted I wouldn't consider the case worth of further investigation. I doubt there're many people facing same issue and the workround if unlikely to be easy and affecting the majority of users (if e.g. I somehow force file metadata updates on each write that can affect the measured figures significantly).

Anyways, thanks for the issue and assistance!

**Comment by Dark-Cod3r** [comment]
Right, Got it. 
Thanks for your assistance too.. 👍
