### ISSUE TITLE
It is not possible to check USB OTG disk speed

### ISSUE THREAD

**Issue by Pablohn26** [maxim-saplin/CrossPlatformDiskTest#7]
When I have to choose the disk to test, I cannot choose the USB OTG flash drive. Android recognizes it without problem, but this app do not.

![photo_2020-02-24_17-27-46](https://user-images.githubusercontent.com/1228418/75170834-fc381c00-572a-11ea-9413-e7eb06992a30.jpg)

**Comment by maxim-saplin** [comment]
Hi, the reason is that the path the path to USB stick is not available via SDK method getExternalFilesDirs. Some phone work well with (e.g. most recent Samsungs) and provide access to USB via SDK, though many phones do not. I deliberately don't go for the option of non-SDK workarounds and tinkering with various manufacturers' specifics of working with USB/SD-Cards.
https://commonsware.com/blog/2019/10/11/storage-situation-removable-storage.html

**Comment by Pablohn26** [comment]
> Hi, the reason is that the path to USB stick is not available via SDK method getExternalFilesDirs. Some phones work well with (e.g. most recent Samsungs) and provide access to USB via the method, though many phones do not. I deliberately don't go for the option of non-SDK workarounds and tinkering with various manufacturers' specifics of working with USB/SD-Cards.
> https://commonsware.com/blog/2019/10/11/storage-situation-removable-storage.html

would Android 10 fix this problem?

**Comment by maxim-saplin** [comment]
Hope so. Didn't have many devices with Android 10  where I coyld try OTG.

**Comment by Theowoll** [comment]
> the reason is that the path to USB stick is not available via SDK method getExternalFilesDirs. Some phones work well with (e.g. most recent Samsungs) and provide access to USB via the method, though many phones do not. I deliberately don't go for the option of non-SDK workarounds and tinkering with various manufacturers' specifics of working with USB/SD-Cards.

Samsung Galaxy Tab S7 with Android 13 is a recent tablet but my USB stick is not listed by CPDT. With Total Commander for Android I find that the USB OTG device is mounted under /mnt/media_rw/XXXX-XXXX. Is this a case of a manufacturer's specific or a limitation of CPDT?

**Comment by maxim-saplin** [comment]
Seems that with newer versions of Android the old API is also no longer working. Just check my S22 with Android 14, it can't see SD card, few years ago it worked.

Yet, there're no plans to discect Android's API changes and find workarounds for externally mounted media
