### ISSUE TITLE
CPDT not booting on Mac installer,

### ISSUE THREAD

**Issue by RickAstley101** [maxim-saplin/CrossPlatformDiskTest#79]
[CPDT.app.zip](https://github.com/maxim-saplin/CrossPlatformDiskTest/files/11240949/CPDT.app.zip)

This is a modified version of the app that will work if it doesn't work for you

**Comment by maxim-saplin** [comment]
Please delete the post. Posting binaries is not a good idea, can be a malicious software that I don't have any relation to.
