### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by Pablohn26** [maxim-saplin/CrossPlatformDiskTest#8]
I would like to translate this app to Spanish.

How should I translate it? just providing [this file](https://github.com/maxim-saplin/CrossPlatformDiskTest/blob/master/Saplin.CPDT.UICore/Localization/L11ns.resx) translated is enough?

**Comment by maxim-saplin** [comment]
Thanks for the suggestion! Translations reside in the following files:
1. https://github.com/maxim-saplin/CrossPlatformDiskTest/blob/master/Saplin.CPDT.UICore/Localization/L11ns.resx
2.https://github.com/maxim-saplin/cpdt_results/blob/master/src/AboutEn.js
3. https://github.com/maxim-saplin/cpdt_results/blob/master/src/translations/en.js
