### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by Cyl18** [maxim-saplin/CrossPlatformDiskTest#9]
![image](https://user-images.githubusercontent.com/14993992/78172840-4f6b6000-7489-11ea-8abc-946c484fcea9.png)
after tested seq write, it just crashed
tried run as admin

windows version 1909

**Comment by maxim-saplin** [comment]
Was there any error message? Did the app show "Seqeuntail write" line(there's none on the screen)?

**Comment by Cyl18** [comment]
I attached a debugger and it shows oom:
![image](https://user-images.githubusercontent.com/14993992/78236945-458b4080-750d-11ea-90da-a69a4f5fd73b.png)
I recorded a video about this:
https://youtu.be/gt1jr9UXVRo

Version is the newest (https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.3.0/CPDT.exe.zip)

**Comment by maxim-saplin** [comment]
Thanks! Seems like 1909 update has broken smth inside Xamarin.Forms... Will look into that

**Comment by maxim-saplin** [comment]
Could you please try this version?
https://www.dropbox.com/s/64sojor4xnw67f2/CPDT.zip?dl=0

**Comment by Cyl18** [comment]
this version works pretty fine!
![image](https://user-images.githubusercontent.com/14993992/78310646-1f06ed00-7581-11ea-8117-0e756bbc6171.png)
good job

therefore I have another question
the memory benchmark has some differents between aida64 
![image](https://user-images.githubusercontent.com/14993992/78310937-fdf2cc00-7581-11ea-9638-334ade8e8fe9.png)

**Comment by maxim-saplin** [comment]
My guess is that AIDA can do the test un multiple threads. CPDT is single threaded. The MemCopy test is quite straightforward, it measures the time it takes to complete the standard .NET array copy routine:
```
            sw.Restart();
            Array.Copy(src, 0, dst, current, src.Length);
            sw.Stop();
```
https://github.com/maxim-saplin/NetCoreStorageSpeedTest/blob/master/Saplin.StorageSpeedMeter/Tests/MemCopyTest.cs

**Comment by Cyl18** [comment]
okay
I googled and found that `Buffer.BlockCopy` might be faster than `Array.Copy`, if you want you can change to that or just use unmanaged to test memory copy
thanks😁
